name: ci
on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet format dotnet-stakeholder.sln --verify-no-changes
      - run: dotnet build dotnet-stakeholder.sln
      - run: dotnet test dotnet-stakeholder.sln
      - if: matrix.os == 'ubuntu-latest'
        run: |
          docker build -t dotnet-stakeholder .
          docker run --rm dotnet-stakeholder --list-values
